### PR TITLE
Add a GitHub action to run test.sh on push and nightly.

### PR DESCRIPTION
**Pull request by mstenta**

### CODE REVIEW

**Comment by mstenta** [comment]
Let's wait and see if this automatically runs the "nightly" tests as well before we merge it in.

**Comment by mstenta** [comment]
The "on push" tests worked: https://github.com/mstenta/farmOS-aggregator/actions/runs/85106907

So anytime a branch gets pushed, it will run `scripts/test.sh`! :-D

**Comment by mstenta** [comment]
I'm not sure if the nightly test ran... not seeing any mention of it here: https://github.com/mstenta/farmOS-aggregator/actions

**Comment by mstenta** [comment]
I noticed there was an extra space between `cron:` and `'0 0 * * *'`, so I fixed and force pushed.

I can't imagine that was what prevented the nightly from running... but I guess we can wait and see tonight?

**Comment by mstenta** [comment]
Well it still doesn't appear that the nightly test is running. I'm not sure how to debug this, or if it's worth doing now anyway.

@paul121 What do you think about me modifying this PR so that it is JUST triggered on pushes. And we can reapproach the nightly testing at another time.

It seems like there is value in just running the tests on pushes right now, and while the nightly tests are nice, I'm not sure what value they add. It's the same result as testing the latest commit, right? Or would it also test dependencies that are potentially changing upstream? Seems like those versions are already pinned and won't be changing in the testing script, would they?

**Comment by paul121** [comment]
@mstenta bummer. Well, we could keep GitLab nightly testing and add the Github action for now. Thats kinda double dipping but shouldn't hurt anything. What do you think about that?

> Or would it also test dependencies that are potentially changing upstream? Seems like those versions are already pinned and won't be changing in the testing script, would they?

Yeah, it would mostly be checking dependencies that are changing upstream. With the recent refactor of the almost all of the dependencies are pinned (especially the important ones, FastAPI, farmOS.py, etc).

I think nightly testing would be great to get going, though. It might prove most useful once we can get full integration tests setup (I don't think that will be too hard .. I already have the testing infrastructure setup we just need to designate a farmOS test server). But we don't need to do that now.

**Comment by mstenta** [comment]
Ok trying another test... I split the "nightly" workflow out to a separate YML file - to see if that makes any difference. And in the process I made the original YML file ONLY for push-triggered runs.

To speed up testing, I temporarily set the "nightly" to run every hour. Let's see how this goes...

**Comment by mstenta** [comment]
That did not work. :-(

**Comment by mstenta** [comment]
Oh!

> Scheduled workflows run on the latest commit on the default or base branch

https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

Maybe this just isn't possible on non-default branches (like this `github-action` branch).

Let me see if I can get it to work on my fork by changing the default branch to `github-action`...

**Comment by mstenta** [comment]
It worked!!!

https://github.com/mstenta/farmOS-aggregator/actions?query=workflow%3A%22Run+tests+nightly%22

**Comment by mstenta** [comment]
I merged the actions back together into one (with two triggers). I think this is ready to go in!

**Comment by paul121** [comment]
@mstenta great!! Thanks for taking another look at CRON - that will be great to have :+1:

**Pull request merged**
